const articles = [
  {
    id: 1,
    title: 'react forever1',
    content: '레엑트는 영원하다1',
    creator: 'do kim',
    modifier: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    id: 2,
    title: 'react forever2',
    content: '레엑트는 영원하다2',
    creator: 'do kim',
    modifier: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    id: 3,
    title: 'react forever3',
    content: '레엑트는 영원하다3',
    creator: 'do kim',
    modifier: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    id: 4,
    title: 'react forever4',
    content: '레엑트는 영원하다',
    creator: 'do kim',
    modifier: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    id: 5,
    title: 'react forever5',
    content: '레엑트는 영원하다',
    creator: 'do kim',
    modifier: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    id: 6,
    title: 'react forever6',
    content: '레엑트는 영원하다',
    creator: 'do kim',
    modifier: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    id: 7,
    title: 'react forever7',
    content: '레엑트는 영원하다',
    creator: 'do kim',
    modifier: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    id: 8,
    title: 'react forever8',
    content: '레엑트는 영원하다',
    creator: 'do kim',
    modifier: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    id: 9,
    title: 'react forever9',
    content: '레엑트는 영원하다',
    creator: 'do kim',
    modifier: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    id: 10,
    title: 'react forever10',
    content: '레엑트는 영원하다',
    creator: 'do kim',
    modifier: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    id: 11,
    title: 'react forever11',
    content: '레엑트는 영원하다',
    creator: 'do kim',
    modifier: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
];

export default articles;