const articles = [
  {
    title: 'react forever1',
    content: '레엑트는 영원하다1',
    writer: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    title: 'react forever2',
    content: '레엑트는 영원하다2',
    writer: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    title: 'react forever3',
    content: '레엑트는 영원하다3',
    writer: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    title: 'react forever4',
    content: '레엑트는 영원하다',
    writer: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    title: 'react forever5',
    content: '레엑트는 영원하다',
    writer: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    title: 'react forever6',
    content: '레엑트는 영원하다',
    writer: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    title: 'react forever7',
    content: '레엑트는 영원하다',
    writer: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    title: 'react forever8',
    content: '레엑트는 영원하다',
    writer: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    title: 'react forever9',
    content: '레엑트는 영원하다',
    writer: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    title: 'react forever10',
    content: '레엑트는 영원하다',
    writer: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
  {
    title: 'react forever11',
    content: '레엑트는 영원하다',
    writer: 'do kim',
    createDate: 123,
    modifiedDate: 134,
  },
];